# Generated by Django 4.2.6 on 2023-11-01 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(choices=[('30 Minutes', '30 Minutes'), ('1 Hour', '1 Hour'), ('1.5 Hours', '1.5 Hours'), ('2 Hours', '2 Hours'), ('2.5 Hours', '2.5 Hours'), ('Up to 6 Hours', 'Up to 6 Hours'), ('More than 6 Hours', 'More than 6 Hours')], default='30 Minutes', max_length=50),
        ),
    ]
