# Generated by Django 4.2.6 on 2023-11-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_recipe_user_alter_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('American', 'American'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Indian', 'Indian'), ('Asian', 'Asian'), ('Other', 'Other')], default='American', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(max_length=3000),
        ),
    ]
